In [12]:
def printall(*args):
    print(*args,args)
printall((1,2,3),(2,))

(1, 2, 3) (2,) ((1, 2, 3), (2,))


In [7]:
args=1,2,3
print(type(args),args)

<class 'tuple'> (1, 2, 3)


In [13]:
a='kiio'
b='kiio'
print(a==b,a is b)

True True


In [14]:
a=[1,2,3]
b=[1,2,3]
print(a==b,a is b)

True False


In [16]:
a.remove(2)
a

[1, 3]

In [17]:
a.pop(0)

1

In [18]:
a

[3]

In [19]:
b

[1, 2, 3]

In [22]:
s='ankit,kiio,summi'
"#".join(s.split(','))

'ankit#kiio#summi'

In [21]:
s='   ankit    '
s.strip()

'ankit'

In [23]:
divmod(7,2)

(3, 1)

In [25]:
divmod(*(7,2))

(3, 1)

In [26]:
args1=(7,2)
args2=7,2
print(args1,args2)

(7, 2) (7, 2)


In [30]:
for a,b in zip([1,2],[3,4]):
    print(a,b)

1 3
2 4


In [31]:
list(zip([1,2],[3,4]))

[(1, 3), (2, 4)]

In [32]:
list(enumerate([3,4]))

[(0, 3), (1, 4)]

In [33]:
import numpy as np
reg=np.random.RandomState(12)
reg.randn(3,4)

array([[ 0.47298583, -0.68142588,  0.2424395 , -1.70073563],
       [ 0.75314283, -1.53472134,  0.00512708, -0.12022767],
       [-0.80698188,  2.87181939, -0.59782292,  0.47245699]])

In [35]:
reg=np.random.RandomState(12)
reg.randn(3,4)

array([[ 0.47298583, -0.68142588,  0.2424395 , -1.70073563],
       [ 0.75314283, -1.53472134,  0.00512708, -0.12022767],
       [-0.80698188,  2.87181939, -0.59782292,  0.47245699]])

In [36]:
reg=np.random.RandomState(12)
reg.randn(3,4)

array([[ 0.47298583, -0.68142588,  0.2424395 , -1.70073563],
       [ 0.75314283, -1.53472134,  0.00512708, -0.12022767],
       [-0.80698188,  2.87181939, -0.59782292,  0.47245699]])

In [37]:
np.random.seed(1)

In [38]:
np.random.randn(3)

array([ 1.62434536, -0.61175641, -0.52817175])

In [39]:
np.random.randn(3)

array([-1.07296862,  0.86540763, -2.3015387 ])

In [41]:
np.random.seed(1)
np.random.randn(3)

array([ 1.62434536, -0.61175641, -0.52817175])

In [42]:
np.random.seed(1)
np.random.randn(3)

array([ 1.62434536, -0.61175641, -0.52817175])

In [43]:
a=12
b='ankit'
'%d is int value and %s is string' % (a,b)

'12 is int value and ankit is string'

In [44]:
'a is {0} '.format(a)

'a is 12 '

In [46]:
import os
os.path.abspath('filename')
os.path.isdir('dirname')
os.path.isfile('filename')
os.path.exists('filename')
os.path.join('filename','dirname')
os.listdir(os.getcwd())

'an 0'

In [48]:
import dbm
x=dbm.open('captions','c')
x['name']='ankit'
print(x['name'])

b'ankit'


In [49]:
import pickle
s=pickle.dumps(np.array([[1,2,3],[4,5,6]]))
pickle.loads(s)

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
import os
os.popen('ls -l').read()

'total 20\ndrwxr-xr-x 1 Ankit19.Gupta 1049089     0 May 24 19:12 General\ndrwxr-xr-x 1 Ankit19.Gupta 1049089     0 May 24 19:10 Summary_ML\ndrwxr-xr-x 1 Ankit19.Gupta 1049089     0 May 24 19:10 Summary_MLOps\ndrwxr-xr-x 1 Ankit19.Gupta 1049089     0 May 24 19:10 Summary_NLP\ndrwxr-xr-x 1 Ankit19.Gupta 1049089     0 May 24 19:12 Summary_Project\ndrwxr-xr-x 1 Ankit19.Gupta 1049089     0 May 24 19:11 Summary_Python\ndrwxr-xr-x 1 Ankit19.Gupta 1049089     0 May 24 19:10 Summary_SQL\ndrwxr-xr-x 1 Ankit19.Gupta 1049089     0 May 24 19:11 Summary_Time_Series\n-rw-r--r-- 1 Ankit19.Gupta 1049089 11445 May 25 15:55 practice.ipynb\n'

In [53]:
#p1 is a point object embedded in a rectangle object and copied the rectangle but point is not copied (shallow copy)
#import copy
#p2=copy.copy(p1)
#copy.deepcopy(box)

In [ ]:
# rectangle has-a (solid arrow) has a point
# a hand is-a (inheritance) (hollow arrow) kind of a deck
# + to __add__ is operator overloading.. < to __lt__
# sum([1,2]+[1,3]) and sum((1,2)) is poymorphism

In [54]:
#generator
gen=(x**2 for x in [1,2,3])
next(gen)

1

In [59]:
def generator():
    for i in range(10):
        yield i**2

In [60]:
obj=generator()
next(obj)

0

In [61]:
next(obj)

1

In [63]:
next(obj) # generator is memory efficient

9

In [67]:
# The * operator doesn’t gather keyword arguments. To gather keyword arguments, you can use the ** operator.
def printall(*args,**kwargs):
    print(args,kwargs)
printall((1,2),5,d=3,x=4)

((1, 2), 5) {'d': 3, 'x': 4}


In [68]:
a='''
I like
kiio
soumi
'''

In [70]:
a=a.replace('like','love')
a

'\nI love\nkiio\nsoumi\n'

In [72]:
a=(1,2,3)
a.count(2)

1

In [73]:
lst=[1,2,3]
lst.insert(2,4)

In [74]:
lst

[1, 2, 4, 3]

In [75]:
d={'ankit':'kiio','summi':'ankit'}
d.pop('summi')
d

{'ankit': 'kiio'}

In [77]:
hash({1,2})

TypeError: unhashable type: 'set'

In [78]:
'   ankit'.split()


['ankit']

In [79]:
'   ankit'.strip()

'ankit'

In [81]:
import re
re.sub('[@%#]','','ank$$#%%#@i%%t  ')

'ank$$it  '

In [84]:
list(map(len,[[1,2],[2,4,5]]))

[2, 3]

In [87]:
my_fun=lambda x: sorted(x)
my_fun([3,2,1])

[1, 2, 3]

In [88]:
for _ in range(3):
    print('ankit',end='#')

ankit#ankit#ankit#

In [2]:
'ankit'.index('k')

2

In [3]:
'ankit'.find('k')

2

In [10]:
import re
text="ankit\n summi\t\t\r kiio   "
reg=re.compile('\s+')
u=reg.split(text)
x=reg.split('I \r\t\n like\n\n    kiio')
print(u,x)

['ankit', 'summi', 'kiio', ''] ['I', 'like', 'kiio']


In [11]:
reg.findall(text)

['\n ', '\t\t\r ', '   ']

In [12]:
u.remove('')

In [13]:
u

['ankit', 'summi', 'kiio']

In [14]:
"ankit\n summi\t\t\r kiio   ".strip()

'ankit\n summi\t\t\r kiio'

In [22]:
reg.split('C:\x')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \xXX escape (2088864503.py, line 1)

In [23]:
reg.split(r'C:\x')

['C:\\x']

In [24]:
reg.findall(r'C:\x')

[]

In [25]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
reg=re.compile(pattern,flags=re.IGNORECASE)

In [26]:
reg

re.compile(r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}', re.IGNORECASE|re.UNICODE)

In [27]:
reg.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [29]:
#substituion
reg.sub('Substituted Text',text)

'Dave Substituted Text\nSteve Substituted Text\nRob Substituted Text\nRyan Substituted Text\n'

In [31]:
reg.sub('Substituted Text',text).split('\n')

['Dave Substituted Text',
 'Steve Substituted Text',
 'Rob Substituted Text',
 'Ryan Substituted Text',
 '']

In [32]:
reg.split(text)

['Dave ', '\nSteve ', '\nRob ', '\nRyan ', '\n']

In [34]:
# for grouping
new_text=reg.findall(text)
print(new_text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']


In [36]:
new_pattern=r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
reg=re.compile(new_pattern,flags=re.IGNORECASE)

In [37]:
lst=[]
for i in new_text:
    m=reg.match(i)
    lst.append(m.groups())

In [38]:
lst

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [39]:
reg.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [40]:
reg.sub(r'Username: \1, Domain: \2, Suffix: \3',text)

'Dave Username: dave, Domain: google, Suffix: com\nSteve Username: steve, Domain: gmail, Suffix: com\nRob Username: rob, Domain: gmail, Suffix: com\nRyan Username: ryan, Domain: yahoo, Suffix: com\n'

In [44]:
import numpy as np
import pandas as pd
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com','Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [45]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [47]:
data.str.findall(new_pattern,flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [48]:
data.str.match(new_pattern,flags=re.IGNORECASE)

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [49]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object